travis:
  secure:
    BINSTAR_TOKEN: ruD+JaC7xZrc5UO8Km0/jseHEuGV90zJRo84HzrfdqnGRyKkk8YewxDKAwQccAX5I5C4T79zXGmyOKAX9hGsl0eVCSV9LARqh2QBbwnbHPcCHRGPL6xnV/Jv/t/1JXBAiRIXeys4AWIEi+keY4Et7rNcfdX8iVWboWxBPpOr4o+Kdy08F1jS8drlqicb0gGJymfZpOrmzMhN0oLVZY0gkQPAoO0sxMcfRzk3RzVyCBa+kll8bGn7lwQUR8Z65MNp8l7dVPYueWP1+NpwE73K+32VUGSKVCSNNbLamy2RFfdufpYsmRo2wlvs4zpWzM+/pLveYHAG6E+VQ2bD7WD0i/sSZ1BnUs7Z1i+1nQ07pEKoDc96yRzl1fCMTc4m2vYZ6RlGHit+WLsbTWeodX3Z7GQRtXjfP/ZNX0mlsnagAg1lqSbEPS89qB9LN8s9yJXoYJEdmv77dqkAlF3CJ/+8EiQtMhUr0DLbSQM3JtNgjwlfQw+BaYoSfCo/Hx99PJmC1iOUvBlUVjlDaAtmowXL4ZYwEBOS0q1o5bQfYJHhh+F2he3IsuuHkd9YynybE/3XndYco6Xg40YepN96MmqW9qWNKbV0/YUb7nzdbnFAyWt+Vu2WWJt2GCPXsBZ+Tc91er7JRPSc/2u3M9t2dV8dweoo0VutEzRZRqRv8PYQbhE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
