travis:
  secure:
    BINSTAR_TOKEN: mRMkXXFsq6yfiTheRfU14RQHJMedeW+x743gX75W+6o3Cw7nkowFyh5v0QCt1yxwZ7efzkTGRs9hOnovK0yxSVoxrxtlLcE+v9HLz4cX9OZ4zpC3NSane95qUTjCcBrq385t1i2LU6EqRLROQsLPN7Dlxtdyll1yHmIJUGNdOzzYA+/Q9m+IugXLm7t1l3rDVhNW2g3QVFrrwwdwtGC7vswxFQLaprwrXlGfwbqnTXErkRNpHX1CbNYmO6m4eQpLsVixmPbSwjt1+cE/ayefxumVy/p8SG4cNC3szdwDcvRlcdhbiTXZBasZ3h2c2nqR9LG9QclE2ro3zwW57XcHjwv8I1NQYPttETnkkzpXtsVDRB0/l2+QsAQgia4xHqYr3EHsGAjmd3oViNMV3/MiZrWFmau9IJLVGCwtUYKFdGDk6ZFqTTHJ2VC5h5wd4UZBgYQis1OG/oCfB7l7zk/MMC5Dm5Tnxc+QsFlY9BfmMTkYtcAy+qQXeqBDmUqPYA39yqYeMPYu15W6OM/q4RnPvwCV6x1Wk0rz3CQOhyEhpg8Dxn28ByvO6rYNt3c8ruMDTd3Dd4mnUrIGvh4oHTVTmRagh2bYhzmv1lPcub0SP5JXv7uR3azAweVLyQHlPEBJY/PScTnyOhgNSwkoaD+1pc7j5NjytAtakT4RjHMs9R0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
